[project]
name = "wiki2"
version = "0.1.0"
description = "Second examenwiki."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
    "markdown2>=2.5.3",
    "pillow>=11.2.1",
    "qrcode>=8.2",
]
