# Generated by Django 5.2.3 on 2025-06-10 15:26

import django.db.models.deletion
import wiki2.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=200, unique=True)),
                ('content', models.TextField(blank=True, help_text='Write your content in Markdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WikiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=wiki2.models.wiki_page_file_path)),
                ('filename_slug', models.SlugField(blank=True, help_text='The slugified name of the file, without extension. Auto-generated if blank.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_files_uploaded', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='wiki2.wikipage')),
            ],
        ),
    ]
