# Generated by Django 5.2.3 on 2025-06-11 19:11

import django.db.models.deletion
import wiki2.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique slug for this exam under its parent page.', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Content in selected format (Markdown or LaTeX).')),
                ('page_type', models.CharField(choices=[('markdown', 'Markdown'), ('latex', 'LaTeX')], default='markdown', help_text='Choose the content type and PDF generation method.', max_length=10)),
                ('pdf_file', models.FileField(blank=True, help_text='Compiled PDF of this exam.', null=True, upload_to=wiki2.models.exam_page_pdf_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_exam_subpages_modified', to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subpages', to='wiki2.wikipage')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('parent_page', 'slug')},
            },
        ),
    ]
