# Generated by Django 5.2.3 on 2025-07-31 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='author',
            field=models.ForeignKey(blank=True, help_text="The owner of this page. Only used for 'Private' pages.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_wiki_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='visibility',
            field=models.CharField(choices=[('LOGGED_IN', 'Logged-in Users'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='LOGGED_IN', help_text='Control who can view this page.', max_length=10),
        ),
    ]
