# Generated by Django 6.0.3 on 2026-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki2', '0002_wikipage_author_wikipage_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the icon (e.g., 'Warning', 'Info')", max_length=50)),
                ('icon', models.FileField(help_text='Upload a square icon (SVG, PNG, etc.)', upload_to='label_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='visibility',
            field=models.CharField(choices=[('LOGGED_IN', 'Logged-In'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='LOGGED_IN', help_text='Control who can view this page.', max_length=10),
        ),
    ]
