# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to the project directory
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull the latest changes from the git repository
            echo ">> Pulling latest code..."
            git pull origin main
            
            # --- NEW PERMISSIONS SECTION ---
            echo ">> Setting correct file permissions..."
            # Change ownership to www-data. The deploy-user needs sudo for this.
            sudo chown -R www-data:www-data .
            # Set directory and file permissions
            sudo find . -type d -exec chmod 775 {} \;
            sudo find . -type f -exec chmod 664 {} \;
            # Make scripts executable
            sudo chmod +x manage.py
            sudo chmod +x *.sh
            # --- END PERMISSIONS SECTION ---
            
            # Rebuild and restart the services
            echo ">> Rebuilding and deploying containers..."
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            
            # Optional: Prune old images to save disk space
            echo ">> Pruning old Docker images..."
            docker image prune -f